name: LibreOffice Fresh

on:
  schedule:
    - cron: "0 18 * * 0"
  workflow_dispatch:

env:
  APPIMAGETOOL_NAME: appimagetool-x86_64.AppImage

jobs:
  build:
    name: Build ${{ matrix.language }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        language: [en-GB, it, ar, zh-CN, zh-TW, fr, de, ja, ko, pt, pt-BR, es, ru, af, am, as, ast, be, bg, bn-IN, bn, bo, br, brx, bs, ca-valencia, ca, cs, cy, da, dgo, dz, el, en-ZA, eo, et, eu, fa, fi, ga, gd, gl, gu, gug, he, hi, hr, hsb, hu, id, is, ka, kk, km, kmr, kn, kok, ks, lb, lo, lt, lv, mai, mk, ml, mn, mni, mr, my, nb, ne, nl, nn, nr, nso, oc, om, or, pa-IN, pl, qtz, ro, rw, sa-IN, sat, sd, si, sid, sk, sl, sq, sr-Latn, sr, ss, st, sv, sw-TZ, ta, te, tg, th, tn, tr, ts, tt, ug, uk, uz, ve, vec, vi, xh, zu]

    steps:
    - uses: actions/checkout@v6

    - name: build
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

        URL="https://github.com/AppImage/appimagetool/releases/download/continuous/${{ env.APPIMAGETOOL_NAME }}"
        wget -c "$URL" -O appimagetool && chmod a+x ./appimagetool
        export PATH="$PWD":"${PATH}"
        
        chmod a+x ./make_libreoffice_appimage
        
        # Build both N and Y variants
        ./make_libreoffice_appimage fresh x86-64 "${{ matrix.language }}" N Y Y Y
        ./make_libreoffice_appimage fresh x86-64 "${{ matrix.language }}" Y Y Y Y
        
        mkdir -p dist
        find . -type d -name out
        mv ./*/*AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: AppImage-${{ matrix.language }}
        path: 'dist'

  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v8
          with:
            path: .
            merge-multiple: true

        # Snapshot Release
        - name: get date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: create snapshot
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot FRESH ${{ env.SNAPSHOT_TAG}}"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false

        # Continuous release
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: LibreOffice FRESH
            automatic_release_tag: continuous-fresh
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
